name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      id: docker_build
      env:
        FULL_IMAGE_NAME: ghcr.io/${{ github.repository }}/map-project
        LOCAL_IMAGE_NAME: map-project
      run: |
        echo "Building Docker image: $FULL_IMAGE_NAME"
        docker build . --file Dockerfile --tag $FULL_IMAGE_NAME:latest

        # Adaugă un tag local simplificat
        docker tag $FULL_IMAGE_NAME:latest $LOCAL_IMAGE_NAME:latest
        
        # Trimite imaginea în registry
        docker push $FULL_IMAGE_NAME:latest
