name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      id: docker_build
      env:
        IMAGE_NAME: map-project
      run: |
        echo "IMAGE_NAME=${{ env.IMAGE_NAME }}"
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest
    